baseUrl=https://dataondemand.bvl.com.pe
#urlCotizaciones=${baseUrl}/v1/stock-quote/home
urlCotizaciones=${baseUrl}/v1/stock-quote/market
urlHora=${baseUrl}/v1/traded-amount/daily
xlsPath=E:/tmp/XLS2/
alarma=2
horaInicio=9:40:00
horaFin=16:30
intervalo=00:05:00
## Cuanto aguanta abierta una alerta antes de cerrarse sola
alertaTimeout=00:10:00
## Port
server.port=8089
## Database
spring.datasource.url=jdbc:h2:file:/tmp/bvldb2
spring.datasource.username=sa
spring.datasource.password=sa
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
## Logging
#logging.level.reactor.netty.http.client=TRACE
logging.level.bvl=DEBUG
logging.level.org.hibernate.type=DEBUG
logging.level.org.hibernate.SQL=DEBUG

