## BVL Settings
baseUrl=https://dataondemand.bvl.com.pe
urlCotizaciones=${baseUrl}/v1/stock-quote/market
urlHora=${baseUrl}/v1/traded-amount/daily
xlsPath=D:/JavaBVL2/XLS2/
alarma=2
horaInicio=9:40:00
horaFin=16:30
intervalo=00:20:00
## Minutos que aguanta abierta una alerta antes de cerrarse sola
alertaTimeout=00:10:00

